### ISSUE TITLE
Syntax Error 

### ISSUE THREAD

**Issue by iansoper** [tylerhall/Autosmush#1]
I'm getting a syntax error when I try to run this script:

Parse error: syntax error, unexpected ',', expecting '(' in /path/to/autosmush on line 120

Any idea why? I'm running  PHP 5.2.5 (cli)

**Comment by tylerhall** [comment]
Not sure what the problem is. The code definitely works on PHP 5.3.2. I don't have a way of testing 5.2.5 at the moment. Perhaps it has something to do with the class constant AmazonS3::ACL_PUBLIC. Try replacing all occurrences with 'public-read'.

**Comment by iansoper** [comment]
I just changed my cli version to PHP 5.3.2 and I'm still getting the same error. Strange.

**Comment by iansoper** [comment]
Ok, I had the right version of php installed... but I didn't change the path in the script, it is working now :)

**Comment by tylerhall** [comment]
Which path did you need to change? Is there something in the README file I should add/update?

**Comment by iansoper** [comment]
On the top of the script: #!/usr/bin/php

I had to change it to: #!/usr/bin/php5
