### ISSUE TITLE
AWS SDK for PHP 2.x Support

### ISSUE THREAD

**Issue by mandersondesign** [tylerhall/Autosmush#11]
Hi Tyler,

Thanks for this awesome tool! I really appreciate your hard work. My question is, will you be updating this to work with the new SDK?  If not, it would be good to be sure to link from your Readme the page to download the 1.6.x version of the SDK, as it took me a bit to figure out I was using the wrong version of the SDK. (It can be found here:http://aws.amazon.com/releasenotes/PHP/4051273386766049)

Anyway, thanks for this great tool!

**Comment by tylerhall** [comment]
Good catch. I've updated the README to link to the 1.6.x version.
