### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by dciphered** [tylerhall/Autosmush#20]
Hi, 

Just wanting to know if this project is active and proven to still work even though the last commit was years ago?

**Comment by tylerhall** [comment]
I really doubt it. I don't think Smush.it has been alive for years. Also, the ideas behind Autosmush have all been superseded by commercial CDNs that automatically compress and optimize your images on the fly.

**Comment by dciphered** [comment]
Thanks for the reply Tyler. Good point RE CDN, AWS CloudFront (which i what I use)however doesn't appear to natively support image compression on the fly without some Lambda integration. Anyways, thanks again.
