### ISSUE TITLE
OMG this is amazing

### ISSUE THREAD

**Issue by boinggg** [tylerhall/Autosmush#4]
Thank you for this. I have one question, is the Smushit integration official or just a hack? Seems hacked from the ajax interface, i don't care. I just wish Yahoo would make it official so this doesn't break out of the blue.

**Comment by tylerhall** [comment]
While I can't say that it's officially supported, based on the post I wrote on the YDN blog, I feel comfortable saying it shouldn't break.

http://developer.yahoo.com/blogs/ydn/posts/2010/10/automatically-compressing-your-amazon-s3-images-using-yahoo’s-smush-it-service/

**Comment by boinggg** [comment]
i saw that. ok cool.
