### ISSUE TITLE
Suggestion : Delete the /tmp file after uploading the smushed file to S3

### ISSUE THREAD

**Issue by saravk** [tylerhall/Autosmush#7]
The script works great for me now. But one issue i found was that the temp files created in the /tmp folder are not deleted. So i added the 'unlink($tmp_filename);' command after the s3 object was updated to delete the temporary file.

The change is working fine for me. I suggest you update the 'official' script as well.

**Comment by tylerhall** [comment]
Thanks! This has been fixed now.
